[es]
    [es.articles]
        host = "http://es64.sonder.fun"
        index = "articles"

[mysql]
    [mysql.articles]
        host = "115.159.110.53"
        port = "3306"
        user = "biaoge"
        passwd = "biaogev587"
        db = "db"
